name: Syntax highlighting bug
description: JS Custom is highlighting your code wrong.
body:
  - type: input
    id: sublime-version
    attributes:
      label: Sublime Text build number
      description: To find the build number, open the command palette and choose “Help: About”. The build number will be on the last line.
  - type: textarea
    id: code
    attributes:
      label: Example Code
      description: Code that triggers the bug. This could be an entire file or a short snippet as long as it triggers the bug by itself.
      render: TSX
    validations:
      required: true
  - type: textarea
    id: settings
    attributes:
      label: JS Custom Preferences
      description: |
        The contents of your JS Custom preferences file. To open your preferences, open the command palette and choose “Preferences: JS Custom”.
      render: JSON with Comments
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is JS Custom doing wrong, and what should it do instead?
